# Generated by Django 5.0.7 on 2024-07-23 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boat_name', models.CharField(help_text='имя лодки', max_length=100)),
                ('boat_capacity', models.IntegerField()),
                ('current_load', models.IntegerField()),
                ('status', models.CharField(help_text='статус', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='boat_id',
        ),
        migrations.RemoveField(
            model_name='tariffs',
            name='boat_id',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='tariff_id',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='manager_id',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='тип уведомления', max_length=50)),
                ('message', models.CharField(help_text='текст уведомления', max_length=250)),
                ('user', models.ForeignKey(help_text='id пользователя', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_amount', models.CharField(choices=[('3D', '3 Дня'), ('5D', '5 Дней'), ('7D', '7 Дней')], help_text='количество дней тарифа', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='стоимость билета', max_digits=20)),
                ('boat', models.ForeignKey(help_text='id лодки', on_delete=django.db.models.deletion.PROTECT, to='main.boat')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creating_date', models.DateTimeField(auto_now_add=True, help_text='дата создания')),
                ('tickets_amount', models.PositiveIntegerField(default=1)),
                ('first_date', models.DateTimeField(help_text='начало путешествия')),
                ('last_date', models.DateTimeField(help_text='конец путешествия')),
                ('status', models.CharField(help_text='статус', max_length=50, null=True)),
                ('boat', models.ForeignKey(help_text='id лодки', on_delete=django.db.models.deletion.PROTECT, to='main.boat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(help_text='id тарифа', on_delete=django.db.models.deletion.PROTECT, to='main.tariff')),
            ],
        ),
        migrations.DeleteModel(
            name='Boats',
        ),
        migrations.DeleteModel(
            name='Tariffs',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
